//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinamikFormYonetimi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public int id { get; set; }
        public bool required { get; set; }
        public string name { get; set; }
        public string dataType { get; set; }
        public int formId { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
